-- 007: Derived analytics + prediction features (all computed locally, never from provider).

CREATE TABLE IF NOT EXISTS league_statistics (
  id                        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  competition_season_id     BIGINT NOT NULL UNIQUE REFERENCES competition_seasons(id) ON DELETE CASCADE,
  matches                   INTEGER,
  completed_matches         INTEGER,
  goals                     INTEGER,
  goals_per_match           NUMERIC(6,3),
  home_goals                INTEGER,
  away_goals                INTEGER,
  home_wins                 INTEGER,
  draws                     INTEGER,
  away_wins                 INTEGER,
  home_win_pct              NUMERIC(5,2),
  draw_pct                  NUMERIC(5,2),
  away_win_pct              NUMERIC(5,2),
  btts_count                INTEGER,
  btts_pct                  NUMERIC(5,2),
  clean_sheet_count         INTEGER,
  clean_sheet_pct           NUMERIC(5,2),
  failed_to_score_count     INTEGER,
  failed_to_score_pct       NUMERIC(5,2),
  yellow_cards              INTEGER,
  yellow_cards_per_match    NUMERIC(6,3),
  second_yellow_cards       INTEGER,
  red_cards                 INTEGER,
  red_cards_per_match       NUMERIC(6,3),
  total_cards               INTEGER,
  cards_per_match           NUMERIC(6,3),
  fouls                     INTEGER,
  fouls_per_match           NUMERIC(6,3),
  penalties                 INTEGER,
  penalties_per_match       NUMERIC(6,3),
  corners                   INTEGER,
  corners_per_match         NUMERIC(6,3),
  shots                     INTEGER,
  shots_per_match           NUMERIC(6,3),
  shots_on_target           INTEGER,
  shots_on_target_per_match NUMERIC(6,3),
  possession_avg            NUMERIC(5,2),
  expected_goals            NUMERIC(8,2),
  expected_goals_per_match  NUMERIC(6,3),
  last_calculated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS team_statistics (
  id                        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  competition_season_id     BIGINT NOT NULL REFERENCES competition_seasons(id) ON DELETE CASCADE,
  team_id                   BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  matches                   INTEGER,
  wins                      INTEGER,
  draws                     INTEGER,
  losses                    INTEGER,
  home_matches              INTEGER,
  home_wins                 INTEGER,
  home_draws                INTEGER,
  home_losses               INTEGER,
  away_matches              INTEGER,
  away_wins                 INTEGER,
  away_draws                INTEGER,
  away_losses               INTEGER,
  goals_for                 INTEGER,
  goals_against             INTEGER,
  goal_difference           INTEGER,
  avg_goals_scored          NUMERIC(6,3),
  avg_goals_conceded        NUMERIC(6,3),
  clean_sheets              INTEGER,
  failed_to_score           INTEGER,
  btts                      INTEGER,
  btts_pct                  NUMERIC(5,2),
  yellow_cards              INTEGER,
  red_cards                 INTEGER,
  total_cards               INTEGER,
  fouls                     INTEGER,
  fouls_per_match           NUMERIC(6,3),
  corners                   INTEGER,
  corners_per_match         NUMERIC(6,3),
  shots                     INTEGER,
  shots_per_match           NUMERIC(6,3),
  shots_on_target           INTEGER,
  shots_on_target_per_match NUMERIC(6,3),
  possession_avg            NUMERIC(5,2),
  expected_goals            NUMERIC(8,2),
  expected_goals_against    NUMERIC(8,2),
  form_last5                TEXT,
  form_last10               TEXT,
  form_last20               TEXT,
  home_form_last10          TEXT,
  away_form_last10          TEXT,
  streaks                   JSONB,
  last_calculated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS team_statistics_unique ON team_statistics (competition_season_id, team_id);

-- player season statistics; team_id NULL = aggregate across teams that season
CREATE TABLE IF NOT EXISTS player_season_statistics (
  id                        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  competition_season_id     BIGINT NOT NULL REFERENCES competition_seasons(id) ON DELETE CASCADE,
  player_id                 BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  team_id                   BIGINT REFERENCES teams(id) ON DELETE CASCADE,
  team_key                  INTEGER NOT NULL GENERATED ALWAYS AS (coalesce(team_id, -1)) STORED,
  appearances               INTEGER,
  starts                    INTEGER,
  minutes                   INTEGER,
  goals                     INTEGER,
  assists                   INTEGER,
  shots                     INTEGER,
  shots_on_target           INTEGER,
  key_passes                INTEGER,
  passes                    INTEGER,
  accurate_passes           INTEGER,
  pass_accuracy_pct         NUMERIC(5,2),
  tackles                   INTEGER,
  interceptions             INTEGER,
  clearances                INTEGER,
  blocks                    INTEGER,
  duels                     INTEGER,
  duels_won                 INTEGER,
  dribbles_attempts         INTEGER,
  dribbles_success          INTEGER,
  fouls_committed           INTEGER,
  fouls_drawn               INTEGER,
  offsides                  INTEGER,
  yellow_cards              INTEGER,
  second_yellow_cards       INTEGER,
  red_cards                 INTEGER,
  penalties_won             INTEGER,
  penalties_committed       INTEGER,
  penalty_goals             INTEGER,
  penalty_misses            INTEGER,
  goalkeeper_saves          INTEGER,
  goals_conceded            INTEGER,
  clean_sheets              INTEGER,
  expected_goals            NUMERIC(8,2),
  expected_assists          NUMERIC(8,2),
  avg_rating                NUMERIC(4,2),
  last_calculated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS player_season_stats_unique
  ON player_season_statistics (competition_season_id, player_id, team_key);
CREATE INDEX IF NOT EXISTS player_season_stats_team_idx ON player_season_statistics (competition_season_id, team_id);

CREATE TABLE IF NOT EXISTS prediction_features (
  id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  fixture_id        BIGINT NOT NULL UNIQUE REFERENCES fixtures(id) ON DELETE CASCADE,
  version           INTEGER NOT NULL DEFAULT 1,
  features          JSONB NOT NULL,
  computed_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS prediction_features_computed_idx ON prediction_features (computed_at DESC);
